/* Replicant - Offline-first Document Sync C API */

#ifndef REPLICANT_H
#define REPLICANT_H

#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace replicant {
#endif // __cplusplus

/**
 * The C ABI version is MAJOR.MINOR. A breaking change bumps the major; an addition (a function,
 * a struct field at the end, an enum value) bumps the minor. A host needs the library's major
 * equal to the header's, and its minor at least the minor that added what the host uses.
 * Hosts treat unknown enum values as unknown: an unknown `ReplicantEventType` is ignored, an
 * unknown `ReplicantHaltReason` is `Other`, an unknown error code is 0 (`Unknown`).
 */
#define REPLICANT_ABI_VERSION_MAJOR 1

/**
 * See `REPLICANT_ABI_VERSION_MAJOR`.
 */
#define REPLICANT_ABI_VERSION_MINOR 0

/**
 * Longest `api_key` or `secret`, in bytes; a buffer for either needs one more for the NUL.
 */
#define REPLICANT_CREDENTIAL_MAX_LEN 128

/**
 * Longest email, in bytes.
 */
#define REPLICANT_EMAIL_MAX_LEN 254

/**
 * A user id's length; its buffer needs one more for the NUL.
 */
#define REPLICANT_USER_ID_LEN 36

enum ReplicantEventOrigin
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  /**
   * A handle of this engine wrote it (this process, this copy of the library): another
   * handle's write on the same engine is `Local` too.
   */
  ReplicantEventOrigin_Local = 0,
  /**
   * Sync wrote it: a download, a settle, a conflict revert or a sweep, in any process.
   */
  ReplicantEventOrigin_Remote = 1,
  /**
   * Another process, or another copy of the library in this process, on the same data dir.
   */
  ReplicantEventOrigin_OtherProcess = 2,
};
#ifndef __cplusplus
typedef int32_t ReplicantEventOrigin;
#endif // __cplusplus

enum ReplicantEventType
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  /**
   * A document was created or changed; `EventOrigin` says by whom.
   */
  ReplicantEventType_DocumentChanged = 1,
  ReplicantEventType_DocumentDeleted = 2,
  ReplicantEventType_SyncStarted = 3,
  /**
   * Every subscribed scope caught up, once per connection. Not a promise that uploads are done.
   */
  ReplicantEventType_SyncCompleted = 4,
  ReplicantEventType_SyncError = 5,
  /**
   * Local content was set aside in Kept copies.
   */
  ReplicantEventType_ConflictDetected = 6,
  ReplicantEventType_ConnectionLost = 7,
  ReplicantEventType_ConnectionAttempted = 8,
  ReplicantEventType_ConnectionSucceeded = 9,
  /**
   * Changes were trimmed before this engine read them, or this handle fell more than 4096
   * events behind: reload every list.
   */
  ReplicantEventType_DatabaseChanged = 11,
  /**
   * The data dir adopted the signed-in account's user id and restamped its documents:
   * re-read `replicant_get_user_id` and reload lists. On the sync callback.
   */
  ReplicantEventType_IdentityAdopted = 12,
};
#ifndef __cplusplus
typedef int32_t ReplicantEventType;
#endif // __cplusplus

enum ReplicantConnection
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  ReplicantConnection_Idle = 0,
  ReplicantConnection_Disconnected = 1,
  ReplicantConnection_Connecting = 2,
  ReplicantConnection_Connected = 3,
  /**
   * Not retrying on its own; see `halt_reason`.
   */
  ReplicantConnection_Halted = 4,
  ReplicantConnection_Stopped = 5,
};
#ifndef __cplusplus
typedef int32_t ReplicantConnection;
#endif // __cplusplus

enum ReplicantErrorCode
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  ReplicantErrorCode_Unknown = 0,
  /**
   * The server refused the credentials; the engine is halted until they change.
   */
  ReplicantErrorCode_AuthInvalid = 1001,
  /**
   * No stored credentials; the engine is halted until someone signs in.
   */
  ReplicantErrorCode_NotEnrolled = 1003,
  /**
   * The server needs a newer client; halted.
   */
  ReplicantErrorCode_UpdateRequired = 2003,
  /**
   * This computer's clock is off; not fatal, the engine keeps retrying.
   */
  ReplicantErrorCode_ClockSkew = 2101,
  ReplicantErrorCode_ProtocolError = 3003,
  /**
   * A subscribed scope was refused and dropped.
   */
  ReplicantErrorCode_SubscriptionForbidden = 3004,
  /**
   * The data dir belongs to another account; halted.
   */
  ReplicantErrorCode_IdentityDrift = 4001,
  ReplicantErrorCode_AccountDisabled = 4002,
  /**
   * The server refused this document's changes; its next local edit retries them. If the
   * refused change was a delete, the server's version is back instead, and edits made before
   * the delete are in Kept copies (`recovered_id`). Also for `Forbidden` and `TooLarge`.
   */
  ReplicantErrorCode_Validation = 5002,
  ReplicantErrorCode_Forbidden = 5003,
  ReplicantErrorCode_TooLarge = 5004,
  /**
   * The document became a read-only publication; unsent edits are in Kept copies.
   */
  ReplicantErrorCode_BecamePublication = 5005,
  /**
   * Its id belongs to another account; the content is in Kept copies.
   */
  ReplicantErrorCode_CreateRejected = 5006,
  /**
   * The server kept storing something other than what was uploaded; the document stops
   * uploading until its next local edit. Local content is kept.
   */
  ReplicantErrorCode_Diverged = 5007,
  /**
   * Reserved: a delete the server refused (the document is back). Not emitted before 0.8;
   * until then a refused delete arrives as `Validation`, `Forbidden` or `TooLarge`.
   */
  ReplicantErrorCode_DeleteRefused = 5008,
  /**
   * The local database failed while checking a join.
   */
  ReplicantErrorCode_LocalDatabase = 6001,
};
#ifndef __cplusplus
typedef int32_t ReplicantErrorCode;
#endif // __cplusplus

enum ReplicantHaltReason
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  ReplicantHaltReason_None = 0,
  /**
   * No stored credentials: sign in.
   */
  ReplicantHaltReason_NotEnrolled = 1,
  /**
   * The server refused the credentials: sign in again.
   */
  ReplicantHaltReason_AuthInvalid = 2,
  /**
   * The server needs a newer client.
   */
  ReplicantHaltReason_UpdateRequired = 3,
  ReplicantHaltReason_AccountDisabled = 4,
  /**
   * This data dir belongs to another account.
   */
  ReplicantHaltReason_IdentityDrift = 5,
  ReplicantHaltReason_Other = 6,
};
#ifndef __cplusplus
typedef int32_t ReplicantHaltReason;
#endif // __cplusplus

/**
 * Merge policy for a list changed on both sides. `ReplicantListMerge_Full` is refused for now.
 */
enum ReplicantListMerge
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  /**
   * Element by element while positions line up on both sides; otherwise the server's list is
   * kept and the local one set aside.
   */
  ReplicantListMerge_Append = 0,
  /**
   * Any change on both sides keeps the server's list and sets the local one aside.
   */
  ReplicantListMerge_Atomic = 1,
  ReplicantListMerge_Full = 2,
};
#ifndef __cplusplus
typedef int32_t ReplicantListMerge;
#endif // __cplusplus

enum ReplicantSync
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  ReplicantSync_Idle = 0,
  ReplicantSync_CatchingUp = 1,
  ReplicantSync_Live = 2,
};
#ifndef __cplusplus
typedef int32_t ReplicantSync;
#endif // __cplusplus

enum ReplicantSyncResult
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  ReplicantSyncResult_Success = 0,
  ReplicantSyncResult_ErrorInvalidInput = -1,
  /**
   * Enrollment only: the server could not be reached.
   */
  ReplicantSyncResult_ErrorConnection = -2,
  ReplicantSyncResult_ErrorDatabase = -3,
  ReplicantSyncResult_ErrorSerialization = -4,
  /**
   * A newer build migrated the database; this build cannot open it.
   */
  ReplicantSyncResult_ErrorNewerSchema = -5,
  /**
   * An engine is open on this data dir with a different server, host or list merge config.
   * A programming error: every binary on a data dir must pass the same config. Never fall
   * back to a temporary library.
   */
  ReplicantSyncResult_ErrorConfigMismatch = -6,
  ReplicantSyncResult_ErrorNotFound = -7,
  /**
   * Another account's document, or a read-only publication.
   */
  ReplicantSyncResult_ErrorNotWritable = -8,
  /**
   * The id exists here or was deleted. An import should skip the id, not count a failure.
   */
  ReplicantSyncResult_ErrorAlreadyExists = -9,
  /**
   * Migrating a v1 library failed; nothing was changed and a `.v1-backup` copy sits next to
   * the database. Show "Your library needs attention"; never fall back to a temporary library.
   */
  ReplicantSyncResult_ErrorMigrationFailed = -10,
  /**
   * Another process kept the database locked; try `replicant_create` again shortly.
   */
  ReplicantSyncResult_ErrorBusy = -11,
  /**
   * `replicant_process_events` was called on another thread than the one that registered.
   */
  ReplicantSyncResult_ErrorWrongThread = -12,
  /**
   * `replicant_process_events` was called before any callback was registered.
   */
  ReplicantSyncResult_ErrorNoCallbacks = -13,
  /**
   * The kept copy's document was deleted: `replicant_restore_document` re-creates the copy.
   */
  ReplicantSyncResult_ErrorDocumentGone = -14,
  /**
   * An output buffer is smaller than the value plus its NUL; see the `REPLICANT_*_LEN` limits.
   */
  ReplicantSyncResult_ErrorBufferTooSmall = -15,
  ReplicantSyncResult_ErrorUnknown = -99,
};
#ifndef __cplusplus
typedef int32_t ReplicantSyncResult;
#endif // __cplusplus

/**
 * Opaque handle. Every call except `replicant_process_events` is thread-safe. Never call from an
 * audio thread: every read and write is a SQLite transaction.
 */
typedef struct Replicant Replicant;

/**
 * Every string is UTF-8 and copied by `replicant_create`.
 */
typedef struct ReplicantConfig {
  /**
   * `sizeof(ReplicantConfig)`. Smaller than the ABI 1.0 struct is refused
   * (`ErrorInvalidInput`); the library reads only the fields it knows.
   */
  uint32_t struct_size;
  /**
   * Holds the database file and the stored credentials.
   */
  const char *data_dir;
  /**
   * File name inside `data_dir`, e.g. "tonaldb.sqlite3".
   */
  const char *database_file;
  const char *server_url;
  /**
   * May be null. Signs joins when the stored credentials carry no email.
   */
  const char *email;
  /**
   * Named in the User-Agent, e.g. "Entonal Studio" and "2.0.1 CLAP".
   */
  const char *host_app;
  const char *host_version;
  /**
   * A `ReplicantListMerge`: how a list both sides changed is merged when no rule matches.
   * An `int32_t` so that a value from C outside the enum is refused, not undefined.
   */
  int32_t list_merge;
  /**
   * May be null. A JSON array of `{"path": "/pitches", "policy": "atomic"}`;
   * policies `append`, `atomic`, `full`. `*` matches one key or index; the rule with the most
   * literal segments wins, a tie goes to the first listed.
   */
  const char *list_merge_rules_json;
} ReplicantConfig;

typedef struct ReplicantState {
  /**
   * Set to `sizeof(ReplicantState)` before `replicant_get_state`; smaller than the ABI 1.0
   * struct is refused. The library writes only the fields it knows and sets this to their
   * size, so a host from a later version can tell which of its fields were filled.
   */
  uint32_t struct_size;
  ReplicantConnection connection;
  ReplicantSync sync;
  ReplicantHaltReason halt_reason;
} ReplicantState;

/**
 * `DocumentChanged` / `DocumentDeleted`. For a deletion only `document_id` is set.
 * `visibility` is `public` (curated or read-only) or `private`.
 * Strings are valid only during the call; copy what you keep.
 */
typedef void (*ReplicantDocumentEventCallback)(ReplicantEventType event_type,
                                               const char *document_id,
                                               const char *title,
                                               const char *content,
                                               const char *owner_id,
                                               const char *author_id,
                                               const char *visibility,
                                               bool read_only,
                                               ReplicantEventOrigin origin,
                                               void *context);

/**
 * `SyncStarted`, `SyncCompleted`, `DatabaseChanged`, `IdentityAdopted`.
 * Strings are valid only during the call; copy what you keep.
 */
typedef void (*ReplicantSyncEventCallback)(ReplicantEventType event_type, void *context);

/**
 * `error_code` is a `ReplicantErrorCode`; `error` is the protocol code, e.g. "clock_skew";
 * `document_id` is null unless the error is about one document; `scope` is null unless it is
 * about one subscribed scope (e.g. `subscription_forbidden`); `fatal` means halted;
 * `recovered_id` names local content kept aside with the error (a Kept copies id, reasons as
 * in `ReplicantConflictEventCallback`), -1 if none.
 * Per engine: only the handles of the engine that applied the rule get this event; another
 * process, or another copy of the library, sees just `DocumentChanged`.
 * `replicant_list_recovered` is the durable record. `recovered_id` may already be dismissed or
 * restored by another process: `restore_*` then returns `ErrorNotFound`.
 * Strings are valid only during the call; copy what you keep.
 */
typedef void (*ReplicantErrorEventCallback)(ReplicantEventType event_type,
                                            int32_t error_code,
                                            const char *error,
                                            const char *document_id,
                                            const char *scope,
                                            bool fatal,
                                            int64_t recovered_id,
                                            void *context);

/**
 * `attempt_number` counts dials since the last successful connection.
 * Strings are valid only during the call; copy what you keep.
 */
typedef void (*ReplicantConnectionEventCallback)(ReplicantEventType event_type,
                                                 bool connected,
                                                 uint32_t attempt_number,
                                                 void *context);

/**
 * `reason`: `conflict`, `field_conflict`, `delete_wins` or `delete_superseded` (a delete undone
 * because a newer version arrived). `recovered_id` is the Kept copies id, -1 if none.
 * A kept copy's reason is one of `conflict`, `field_conflict`, `delete_wins`,
 * `delete_superseded`, `delete_refused`, `delete_publication`, `became_publication`,
 * `create_rejected` or `unmigratable` (set aside while upgrading the database, with no event).
 * `paths_json` is a JSON array of JSON Pointers for `field_conflict`, else null.
 * Per engine: only the handles of the engine that applied the rule get this event; another
 * process, or another copy of the library, sees just `DocumentChanged`.
 * `replicant_list_recovered` is the durable record. `recovered_id` may already be dismissed or
 * restored by another process: `restore_*` then returns `ErrorNotFound`.
 * Strings are valid only during the call; copy what you keep.
 */
typedef void (*ReplicantConflictEventCallback)(ReplicantEventType event_type,
                                               const char *document_id,
                                               const char *reason,
                                               int64_t recovered_id,
                                               const char *paths_json,
                                               void *context);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Whether `code` (a `ReplicantErrorCode`) means the credentials were refused or are missing.
 */
bool replicant_error_is_credential_rejection(int32_t code);

/**
 * The library's ABI version, packed: `(major << 16) | minor`.
 */
uint32_t replicant_abi_version(void);

/**
 * Attaches to the engine for `config`'s data dir, starting it if this process has none yet.
 * Opens (and after an upgrade migrates) the database on this thread; never waits on the
 * network. On success `*out_handle` is set; otherwise it is null. Call `replicant_get_state`
 * next: a handle attached to an engine that is already halted is not sent the halt again.
 *
 * # Safety
 * `config` and `out_handle` must be valid; the config's strings valid C strings (`email` may be null).
 */
ReplicantSyncResult replicant_create(const struct ReplicantConfig *config,
                                     struct Replicant **out_handle);

/**
 * Detaches and frees the handle. Returns at once: when this was the engine's last handle, the
 * engine stops on a Replicant thread afterwards (never waiting on the network). Called from
 * inside one of this handle's callbacks, the free happens when `replicant_process_events`
 * returns.
 *
 * Unloading: library code can still run after this returns, and even after
 * `replicant_destroy_and_wait` returns true, because a DNS lookup the engine started finishes
 * on its own thread, bounded only by the OS resolver. Never unload this library while the
 * process runs: a plugin pins its module (`RTLD_NODELETE`, or
 * `GET_MODULE_HANDLE_EX_FLAG_PIN` on Windows).
 *
 * # Safety
 * `handle` must come from `replicant_create` and not be used again.
 */
void replicant_destroy(struct Replicant *handle);

/**
 * `replicant_destroy`, then waits up to `timeout_ms` for the engine to stop and its runtime to
 * shut down. True when it has, or when other handles keep the engine running. It does not make
 * unloading safe (see `replicant_destroy`). From inside a
 * callback it cannot wait: it returns false and the handle is freed when the pump returns.
 *
 * # Safety
 * As `replicant_destroy`.
 */
bool replicant_destroy_and_wait(struct Replicant *handle, uint32_t timeout_ms);

/**
 * Creates a document owned by the signed-in (or provisional) user; writes its id into
 * `out_document_id` (37 bytes).
 *
 * # Safety
 * Valid handle, C string, and a 37-byte buffer.
 */
ReplicantSyncResult replicant_create_document(struct Replicant *handle,
                                              const char *content_json,
                                              char *out_document_id);

/**
 * Creates a document with a chosen id. Refused (`ErrorAlreadyExists`) when the id exists here
 * or was deleted.
 *
 * # Safety
 * Valid handle and C strings.
 */
ReplicantSyncResult replicant_create_document_with_id(struct Replicant *handle,
                                                      const char *document_id,
                                                      const char *content_json);

/**
 * # Safety
 * Valid handle and C strings.
 */
ReplicantSyncResult replicant_update_document(struct Replicant *handle,
                                              const char *document_id,
                                              const char *content_json);

/**
 * # Safety
 * Valid handle and C string.
 */
ReplicantSyncResult replicant_delete_document(struct Replicant *handle, const char *document_id);

/**
 * The document as JSON: `id`, `user_id` (owner), `author_id`, `title`, `content`, `read_only`,
 * `visibility` (`public`/`private`), `source_doc_id`, `derived_from`, `created_at`,
 * `updated_at`. `ErrorNotFound` when missing or deleted.
 *
 * # Safety
 * Valid handle, C string and out pointer; free the result with `replicant_string_free`.
 */
ReplicantSyncResult replicant_get_document(struct Replicant *handle,
                                           const char *document_id,
                                           char **out_json);

/**
 * Every visible document as a JSON array (see `replicant_get_document`).
 *
 * # Safety
 * Valid handle and out pointer; free the result with `replicant_string_free`.
 */
ReplicantSyncResult replicant_get_all_documents(struct Replicant *handle, char **out_json);

/**
 * Document ids as a JSON array; `include_deleted` adds documents whose delete is not yet sent.
 *
 * # Safety
 * Valid handle and out pointer; free the result with `replicant_string_free`.
 */
ReplicantSyncResult replicant_get_all_document_ids(struct Replicant *handle,
                                                   bool include_deleted,
                                                   char **out_json);

/**
 * # Safety
 * Valid handle and out pointer.
 */
ReplicantSyncResult replicant_count_documents(struct Replicant *handle, uint64_t *out_count);

/**
 * Documents with changes the server has not acknowledged, except parked ones (`replicant_list_parked`).
 *
 * # Safety
 * Valid handle and out pointer.
 */
ReplicantSyncResult replicant_count_pending_sync(struct Replicant *handle,
                                                 uint64_t *out_count);

/**
 * # Safety
 * `handle` must be valid or null.
 */
bool replicant_is_connected(struct Replicant *handle);

/**
 * Connection, sync phase and halt reason, for a status indicator. Set
 * `out_state->struct_size = sizeof(ReplicantState)` first.
 *
 * # Safety
 * Valid handle and out pointer.
 */
ReplicantSyncResult replicant_get_state(struct Replicant *handle, struct ReplicantState *out_state);

/**
 * Leaves `Halted` or retries now. Safe to call repeatedly: the engine dials at most once a second.
 *
 * # Safety
 * Valid handle.
 */
ReplicantSyncResult replicant_reconnect(struct Replicant *handle);

/**
 * The data dir's user id (provisional until the first join).
 *
 * # Safety
 * Valid handle and out pointer; free the result with `replicant_string_free`.
 */
ReplicantSyncResult replicant_get_user_id(struct Replicant *handle, char **out_user_id);

/**
 * # Safety
 * Valid handle and C string (a JSON array of JSON paths, e.g. `["$.body"]`).
 */
ReplicantSyncResult replicant_configure_search(struct Replicant *handle, const char *paths_json);

/**
 * FTS5 query (`music`, `tun*`, `"a phrase"`, `a AND b`, `title:word`); `limit` 0 means 100. A
 * query FTS5 cannot parse is `ErrorInvalidInput`.
 *
 * # Safety
 * Valid handle, C string and out pointer; free the result with `replicant_string_free`.
 */
ReplicantSyncResult replicant_search_documents(struct Replicant *handle,
                                               const char *query,
                                               uint32_t limit,
                                               char **out_json);

/**
 * # Safety
 * Valid handle.
 */
ReplicantSyncResult replicant_rebuild_search_index(struct Replicant *handle);

/**
 * Kept copies (local content sync set aside), newest first, as a JSON array of
 * `{recovered_id, doc_id, title, reason, recovered_at, content, fields}`. `reason` is
 * `conflict`, `field_conflict`, `delete_wins`, `delete_superseded`, `delete_refused`,
 * `delete_publication`, `became_publication`, `create_rejected` or `unmigratable` (set aside
 * while upgrading the database). `fields` is null for a whole-document copy, else `[{path, local_value, local_removed}]`.
 * Copies never expire: they stay until dismissed or restored.
 *
 * # Safety
 * Valid handle and out pointer; free the result with `replicant_string_free`.
 */
ReplicantSyncResult replicant_list_recovered(struct Replicant *handle,
                                             char **out_json);

/**
 * Deletes a kept copy for good; `ErrorNotFound` when it is already gone.
 *
 * # Safety
 * Valid handle.
 */
ReplicantSyncResult replicant_dismiss_recovered(struct Replicant *handle, int64_t recovered_id);

/**
 * Re-creates a kept copy's full content as a new document, with a new id written to
 * `out_document_id` (37 bytes), and removes the copy. Works for any copy, a field copy too
 * (the way out when its document is gone). `ErrorNotFound` when the copy is gone (another
 * process may have dismissed or restored it).
 *
 * # Safety
 * Valid handle and a 37-byte buffer.
 */
ReplicantSyncResult replicant_restore_document(struct Replicant *handle,
                                               int64_t recovered_id,
                                               char *out_document_id);

/**
 * Writes a field copy's kept values back at their paths as a local edit (every other field
 * keeps its current value) and removes the copy.
 *
 * A list conflict is kept as the whole list, so restoring it puts that list back exactly.
 * `ErrorNotFound`: the copy is gone. `ErrorDocumentGone`: its document was deleted, and
 * `ErrorNotWritable`: it became read-only; the copy stays in both cases, and
 * `replicant_restore_document` brings it back as a new document.
 *
 * # Safety
 * Valid handle.
 */
ReplicantSyncResult replicant_restore_fields(struct Replicant *handle, int64_t recovered_id);

/**
 * Documents that stopped uploading until their next local edit, as a JSON array of
 * `{doc_id, code}` (`validation`, `forbidden`, `too_large`, `diverged`). Parked documents are
 * not counted in `replicant_count_pending_sync`; a new local edit un-parks one.
 *
 * # Safety
 * Valid handle and out pointer; free the result with `replicant_string_free`.
 */
ReplicantSyncResult replicant_list_parked(struct Replicant *handle, char **out_json);

/**
 * `event_filter`: -1 every document event, 1 `DocumentChanged` only, 2 `DocumentDeleted` only.
 * One callback per kind: registering again replaces the previous callback, filter and context;
 * a null callback removes it (its events are then dropped when pumped). The first registration
 * on a handle, of any kind, fixes the thread that must call `replicant_process_events`.
 *
 * # Safety
 * Valid handle; `context` must outlive the handle.
 */
ReplicantSyncResult replicant_register_document_callback(struct Replicant *handle,
                                                         ReplicantDocumentEventCallback callback,
                                                         void *context,
                                                         int32_t event_filter);

/**
 * `SyncStarted`, `SyncCompleted`, `DatabaseChanged` and `IdentityAdopted`. Replaces or removes
 * as `replicant_register_document_callback` does.
 *
 * # Safety
 * Valid handle; `context` must outlive the handle.
 */
ReplicantSyncResult replicant_register_sync_callback(struct Replicant *handle,
                                                     ReplicantSyncEventCallback callback,
                                                     void *context);

/**
 * Replaces or removes as `replicant_register_document_callback` does.
 *
 * # Safety
 * Valid handle; `context` must outlive the handle.
 */
ReplicantSyncResult replicant_register_error_callback(struct Replicant *handle,
                                                      ReplicantErrorEventCallback callback,
                                                      void *context);

/**
 * Replaces or removes as `replicant_register_document_callback` does.
 *
 * # Safety
 * Valid handle; `context` must outlive the handle.
 */
ReplicantSyncResult replicant_register_connection_callback(struct Replicant *handle,
                                                           ReplicantConnectionEventCallback callback,
                                                           void *context);

/**
 * Replaces or removes as `replicant_register_document_callback` does.
 *
 * # Safety
 * Valid handle; `context` must outlive the handle.
 */
ReplicantSyncResult replicant_register_conflict_callback(struct Replicant *handle,
                                                         ReplicantConflictEventCallback callback,
                                                         void *context);

/**
 * Runs the callbacks for every queued event. Must be called on the thread that registered
 * the callbacks: refused with `ErrorWrongThread` elsewhere and `ErrorNoCallbacks` before any
 * registration; nothing is lost either way. The thread cannot be changed later. A
 * `replicant_destroy` of this handle from inside a callback frees it when this call returns;
 * the rest of the batch is not delivered. A call from inside a callback returns
 * `ErrorInvalidInput`. No rebind: if the registering thread ends, register again on a new
 * handle.
 *
 * # Safety
 * Valid handle; `out_processed_count` may be null.
 */
ReplicantSyncResult replicant_process_events(struct Replicant *handle,
                                             uint32_t *out_processed_count);

/**
 * # Safety
 * `s` must come from this library and not be freed twice.
 */
void replicant_string_free(char *s);

/**
 * This library's version, e.g. "0.7.0". Static: never free it.
 */
const char *replicant_get_version(void);

/**
 * Requests an enrollment token be emailed to `email`. Needs no handle. Blocks the calling
 * thread for the HTTP round trip (up to about 10 s to connect and 30 s for the request); never
 * call it from an audio or UI thread.
 *
 * # Safety
 * `base_url` and `email` must be valid, non-null C strings.
 */
ReplicantSyncResult replicant_enroll_request(const char *base_url, const char *email);

/**
 * Exchanges an enrollment token for credentials and stores them in `data_dir` with `email`,
 * as `replicant_store_credentials` does, before writing the api key, secret and user id into
 * the buffers (each `*_cap` is its buffer's size). A buffer too small for its value is
 * `ErrorBufferTooSmall`, and the credentials are stored all the same: the token is spent.
 * `ErrorInvalidInput`: the token was refused. `ErrorSerialization`: the server's reply was bad.
 * `ErrorConnection`: the server could not be reached. Out buffers are only valid on `Success`.
 *
 * Blocks the calling thread for the HTTP round trip (up to about 10 s to connect and 30 s for
 * the request); never call it from an audio or UI thread.
 *
 * # Safety
 * All string pointers must be valid, non-null C strings; each out pointer
 * must reference a writable buffer of at least its stated capacity.
 */
ReplicantSyncResult replicant_enroll_claim(const char *base_url,
                                           const char *data_dir,
                                           const char *email,
                                           const char *token,
                                           char *out_api_key,
                                           size_t api_key_cap,
                                           char *out_secret,
                                           size_t secret_cap,
                                           char *out_user_id,
                                           size_t user_id_cap);

/**
 * Loads the credentials stored in `data_dir` into the buffers (each `*_cap` is its buffer's
 * size; see the `REPLICANT_*_LEN` limits). `ErrorNotFound`: none are stored.
 * `ErrorDatabase`: they cannot be read. `ErrorBufferTooSmall`: a buffer is too small. Out
 * buffers are only valid on `Success`.
 *
 * # Safety
 * `data_dir` must be a valid, non-null C string; each out pointer must
 * reference a writable buffer of at least its stated capacity.
 */
ReplicantSyncResult replicant_load_credentials(const char *data_dir,
                                               char *out_api_key,
                                               size_t api_key_cap,
                                               char *out_secret,
                                               size_t secret_cap,
                                               char *out_user_id,
                                               size_t user_id_cap);

/**
 * Stores credentials in `data_dir` (encrypted at rest) and tells this process's engines on
 * that data dir. `email` (may be null; `""` counts as none) signs joins; `user_id` must be a
 * real UUID. A value longer than its `REPLICANT_*_LEN` limit is `ErrorInvalidInput`.
 *
 * # Safety
 * Valid C strings; `email` may be null.
 */
ReplicantSyncResult replicant_store_credentials(const char *data_dir,
                                                const char *email,
                                                const char *api_key,
                                                const char *secret,
                                                const char *user_id);

/**
 * Removes the stored credentials (sign-out) and tells this process's engines on `data_dir`:
 * they halt as not enrolled and never join with the removed credentials. An engine in another
 * process ends its live connection within about a second and never joins with the removed
 * credentials.
 *
 * # Safety
 * Valid C string.
 */
ReplicantSyncResult replicant_clear_credentials(const char *data_dir);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#ifdef __cplusplus
} // namespace replicant
#endif // __cplusplus

#endif /* REPLICANT_H */
