/* Replicant - Offline-first Document Sync C API */

#ifndef REPLICANT_H
#define REPLICANT_H

#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace replicant {
#endif // __cplusplus

/**
 * Where a document event came from.
 *
 * Document events are emitted for this client's own writes as well as for
 * changes applied from the server, and the rest of the payload cannot tell the
 * two apart: `user_id` is the document owner, not the writer, and delivery is
 * asynchronous. Consumers that only care about changes made elsewhere should
 * ignore `Local` events.
 */
typedef enum ReplicantEventOrigin {
  /**
   * This client wrote the document itself.
   */
  Local = 0,
  /**
   * The change was applied from the server: a broadcast from another client
   * or instance, or a sync pass.
   */
  Remote = 1,
} ReplicantEventOrigin;

/**
 * Event types that can be emitted by the sync client
 */
typedef enum ReplicantEventType {
  /**
   * A new document was created.
   *
   * Fires for THIS client's own `create_document` call as well as for a
   * document that arrived from the server. Check the event's origin before
   * treating it as a change made elsewhere.
   */
  DocumentCreated = 0,
  /**
   * An existing document was updated.
   *
   * Fires for THIS client's own `update_document` call as well as for a
   * patch applied from the server. Check the event's origin before treating
   * it as a change made elsewhere.
   */
  DocumentUpdated = 1,
  /**
   * A document was deleted.
   *
   * Fires for THIS client's own `delete_document` call as well as for a
   * deletion applied from the server. Check the event's origin before
   * treating it as a change made elsewhere.
   */
  DocumentDeleted = 2,
  /**
   * Synchronization process started
   */
  SyncStarted = 3,
  /**
   * Synchronization completed successfully
   */
  SyncCompleted = 4,
  /**
   * An error occurred during synchronization
   */
  SyncError = 5,
  /**
   * A conflict was detected between document versions
   */
  ConflictDetected = 6,
  /**
   * Connection to server was lost
   */
  ConnectionLost = 7,
  /**
   * A connection attempt was made to the server
   */
  ConnectionAttempted = 8,
  /**
   * Successfully connected to the server
   */
  ConnectionSucceeded = 9,
  /**
   * The server-authoritative user id was adopted, replacing the local one
   */
  IdentityChanged = 10,
} ReplicantEventType;

/**
 * Structured error code carried by every `SyncError` event.
 *
 * The numeric values are STABLE and exported to C via cbindgen. They are
 * banded by the action a consumer should take:
 *
 * - `0` — unknown / uncategorized.
 * - `1xxx` — **credential rejected**: the stored credential is bad. The
 *   consumer should clear it and re-enroll. See [`is_credential_rejection`].
 * - `2xxx` — **transient**: retry later; NEVER clear credentials. This band
 *   includes the timestamp reasons (`2101`, `2102`), which are client/server
 *   clock skew — not a bad credential — and so must never trigger a clear.
 * - `3xxx` — **protocol**: the exchange was malformed or violated the contract.
 * - `4xxx` — **identity drift**: the local identity diverged from the account;
 *   refuse to sync, but do NOT clear credentials.
 * - `5xxx` — **unresolved divergence**: a local edit could not be reconciled
 *   with the server's copy. Retrying cannot help; surface it to the user.
 */
enum ReplicantErrorCode
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  /**
   * Unknown or uncategorized error.
   */
  Unknown = 0,
  /**
   * The API key is not recognized by the server.
   */
  InvalidApiKey = 1001,
  /**
   * The HMAC signature did not verify.
   */
  InvalidSignature = 1002,
  /**
   * The credential authenticated but is not bound to an enrolled user.
   */
  CredentialNotEnrolled = 1003,
  /**
   * The socket/transport failed to connect.
   */
  ConnectionFailed = 2001,
  /**
   * A join or call timed out.
   */
  Timeout = 2002,
  /**
   * The signed timestamp was outside the server's acceptance window
   * (client/server clock skew, not a bad credential).
   */
  TimestampExpired = 2101,
  /**
   * The timestamp field was malformed or unparseable (treated as clock skew).
   */
  InvalidTimestamp = 2102,
  /**
   * A required join parameter was missing.
   */
  MissingParams = 3001,
  /**
   * The join topic's user id did not match the credential's user.
   */
  TopicUserMismatch = 3002,
  /**
   * Generic malformed or unexpected server reply.
   */
  ProtocolError = 3003,
  /**
   * The server-reported user id diverged from the local identity.
   */
  IdentityDrift = 4001,
  /**
   * A local edit could not be rebased onto the server's current content.
   * The server's copy is now local truth and the edit was discarded.
   */
  UpdateConflict = 5001,
};
#ifndef __cplusplus
typedef int32_t ReplicantErrorCode;
#endif // __cplusplus

/**
 * Result codes for C API functions
 */
typedef enum ReplicantSyncResult {
  Success = 0,
  ErrorInvalidInput = -1,
  ErrorConnection = -2,
  ErrorDatabase = -3,
  ErrorSerialization = -4,
  ErrorUnknown = -99,
} ReplicantSyncResult;

/**
 * Opaque handle to a Replicant client instance
 */
typedef struct Replicant Replicant;

/**
 * Document event callback for DocumentCreated, DocumentUpdated, DocumentDeleted
 *
 * Fires for this client's OWN writes as well as for changes applied from the
 * server. Check `origin` before treating an event as a change made elsewhere.
 *
 * # Parameters
 * * `event_type` - The specific document event type
 * * `document_id` - UUID of the document (always non-null)
 * * `title` - Document title (null for Deleted events)
 * * `content` - Full document JSON (null for Deleted events)
 * * `user_id` - Owner UUID (null if unknown)
 * * `author_name` - Author display name (null if unknown)
 * * `visibility` - "private"/"public" (null if unknown)
 * * `origin` - `Local` if this client wrote the document, `Remote` if the
 *   change was applied from the server
 * * `context` - User-defined context pointer
 */
typedef void (*DocumentEventCallback)(enum ReplicantEventType event_type,
                                      const char *document_id,
                                      const char *title,
                                      const char *content,
                                      const char *user_id,
                                      const char *author_name,
                                      const char *visibility,
                                      enum ReplicantEventOrigin origin,
                                      void *context);

/**
 * Sync event callback for SyncStarted, SyncCompleted
 *
 * # Parameters
 * * `event_type` - SyncStarted or SyncCompleted
 * * `document_count` - Number of documents synced (0 for SyncStarted)
 * * `context` - User-defined context pointer
 */
typedef void (*SyncEventCallback)(enum ReplicantEventType event_type,
                                  uint64_t document_count,
                                  void *context);

/**
 * Error event callback for SyncError
 *
 * # Parameters
 * * `event_type` - Always SyncError
 * * `error_code` - Stable `ReplicantErrorCode` value; use
 *   `replicant_error_is_credential_rejection` to decide whether to clear the
 *   stored credential
 * * `error` - Error message (always non-null)
 * * `context` - User-defined context pointer
 */
typedef void (*ErrorEventCallback)(enum ReplicantEventType event_type,
                                   int32_t error_code,
                                   const char *error,
                                   void *context);

/**
 * Connection event callback for ConnectionLost, ConnectionAttempted, ConnectionSucceeded
 *
 * # Parameters
 * * `event_type` - The connection event type
 * * `connected` - true if connected (valid for Lost/Succeeded), false otherwise
 * * `attempt_number` - Reconnection attempt number (valid for ConnectionAttempted)
 * * `context` - User-defined context pointer
 */
typedef void (*ConnectionEventCallback)(enum ReplicantEventType event_type,
                                        bool connected,
                                        uint32_t attempt_number,
                                        void *context);

/**
 * Conflict event callback for ConflictDetected
 *
 * # Parameters
 * * `event_type` - Always ConflictDetected
 * * `document_id` - UUID of the conflicted document (always non-null)
 * * `winning_content` - Content of the winning version (always non-null)
 * * `losing_content` - Content of the losing version (may be null)
 * * `context` - User-defined context pointer
 */
typedef void (*ConflictEventCallback)(enum ReplicantEventType event_type,
                                      const char *document_id,
                                      const char *winning_content,
                                      const char *losing_content,
                                      void *context);

/**
 * Identity event callback for IdentityChanged
 *
 * # Parameters
 * * `event_type` - Always IdentityChanged
 * * `old_user_id` - The provisional/previous user id (always non-null)
 * * `new_user_id` - The adopted canonical user id (always non-null)
 * * `email` - The email the server resolved the id from (may be empty)
 * * `context` - User-defined context pointer
 */
typedef void (*IdentityEventCallback)(enum ReplicantEventType event_type,
                                      const char *old_user_id,
                                      const char *new_user_id,
                                      const char *email,
                                      void *context);

/**
 * Document structure for C API
 */
typedef struct Document {
  char *id;
  char *title;
  char *content;
  int64_t sync_revision;
} Document;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Band check exposed over FFI: `true` iff `code` is a credential rejection.
 *
 * Bindings should treat a `true` result as "clear the stored credential and
 * re-enroll". Implemented once here so consumers do not re-implement the band
 * logic against the raw numeric values.
 *
 * # Safety
 * This function is pure and takes the code by value; it is always safe to call.
 */
bool replicant_error_is_credential_rejection(int32_t code);

/**
 * Create a new sync engine instance
 *
 * # Arguments
 * * `database_url` - SQLite database URL (e.g., "sqlite:client.db?mode=rwc")
 * * `server_url` - WebSocket server URL (e.g., "ws://localhost:8080/ws")
 * * `email` - User email address
 * * `api_key` - Application API key (rpa_ prefix)
 * * `api_secret` - Application API secret (rps_ prefix)
 *
 * # Returns
 * * Pointer to SyncEngine on success, null on failure
 *
 * # Safety
 * Caller must ensure all pointers are valid, non-null C strings
 */
struct Replicant *replicant_create(const char *database_url,
                                   const char *server_url,
                                   const char *email,
                                   const char *api_key,
                                   const char *api_secret,
                                   const char *user_id);

/**
 * Destroy a sync engine instance and free memory
 *
 * NON-BLOCKING, fire-and-forget: it returns immediately and the teardown —
 * closing both sqlite pools and joining this instance's threads — finishes on
 * a Replicant-owned thread afterwards. The handle is invalid the moment this
 * returns; no further call may use it.
 *
 * This is safe to call on a UI or audio-host thread (plugin scans, project
 * close) precisely because it does not wait. The consequence is that threads
 * Replicant started can still be running Replicant code for a short time after
 * it returns — normally milliseconds, longer if sqlite is contended.
 *
 * THEREFORE: any caller that can be UNLOADED FROM MEMORY — every plugin —
 * MUST make sure its own binary is never unmapped, or one of those threads
 * will be executing code at an address that no longer exists (the DEV-1118
 * crash: an execute access violation on an unmapped image). Pin the module
 * once, at load:
 *
 *   * Windows: `GetModuleHandleExW` with `GET_MODULE_HANDLE_EX_FLAG_PIN`
 *     (plus `GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS`) on an address in your
 *     own module.
 *   * macOS / Linux: `dlopen` your own image with `RTLD_NOLOAD | RTLD_NODELETE`.
 *
 * Pinning is the primary defence, not a workaround. A host process that only
 * ever exits (a standalone app) does not need it; anything a host can unload
 * does.
 *
 * UPGRADING FROM 0.6.2 OR EARLIER WITHOUT PINNING IS A REGRESSION. The old
 * destroy dropped the handle, which joined the tokio runtime's threads before
 * returning and left only sqlx's workers running; this one returns with the
 * background init, both pools, the runtime's threads and the sqlx workers all
 * still live. The total time any thread of ours is alive goes down — the pools
 * are now actually closed, so nothing lingers for the life of the process — but
 * the exposure *at the moment destroy returns* goes up.
 *
 * A second instance may be created immediately; it shares nothing with the one
 * being torn down. Note only that the outgoing instance may still be writing to
 * the same database file for a moment, so an immediate re-create against it can
 * see sqlite contention (and `replicant_create` returns NULL if that outlasts
 * sqlite's 5s busy timeout). `replicant_destroy_and_wait` avoids the overlap.
 *
 * Callers that *can* afford to wait — standalone apps shutting down, tests —
 * should use `replicant_destroy_and_wait` instead, which reports whether the
 * teardown actually finished.
 *
 * # Safety
 * Caller must ensure engine pointer was created by replicant_create and hasn't been freed.
 * As with any free function, no other call on this handle may be in progress on
 * any thread — which includes destroying it from inside a Replicant callback
 * while the call that dispatched that callback is still on the stack.
 */
void replicant_destroy(struct Replicant *engine);

/**
 * Destroy a sync engine instance and wait for its teardown to finish.
 *
 * Same as `replicant_destroy` (the handle is invalid either way, whatever this
 * returns) but BLOCKS for up to `timeout_ms` waiting for Replicant to close
 * its sqlite pools and join its threads.
 *
 * Returns `true` when the teardown completed: no REPLICANT-OWNED thread — its
 * tokio runtime, its sqlite workers — is running any more. That is the claim,
 * and it is narrower than "this module has no threads in it": libraries linked
 * into Replicant (the WebSocket and TLS stacks in particular) may keep threads
 * of their own that Replicant neither owns nor can join, so a module that has
 * ever connected should still be pinned rather than unloaded.
 *
 * Returns `false` if the wait ran out, or if the caller cannot wait (destroy
 * from inside a Replicant callback on a Replicant runtime thread) — the teardown
 * then carries on in the background.
 *
 * `timeout_ms` of 0 does not wait at all; it reports whether the teardown had
 * already finished. Pass a large value (`UINT32_MAX`) to wait in effect
 * indefinitely.
 *
 * Intended for standalone applications and tests. A plugin should call
 * `replicant_destroy` and pin its module instead of blocking a host thread.
 *
 * # Safety
 * Caller must ensure engine pointer was created by replicant_create and hasn't been freed
 */
bool replicant_destroy_and_wait(struct Replicant *engine, uint32_t timeout_ms);

/**
 * Create a new document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `content_json` - Document content as JSON string (should include any title as part of the JSON)
 * * `out_document_id` - Output buffer for document ID (must be at least 37 chars)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, content_json is a valid C string, and out_document_id has space for 37 bytes
 */
enum ReplicantSyncResult replicant_create_document(struct Replicant *engine,
                                                   const char *content_json,
                                                   char *out_document_id);

/**
 * Create a new document with a specified ID
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - UUID string to use as the document ID
 * * `content_json` - Document content as JSON string
 *
 * # Returns
 * * `SyncResult::Success` - Document created successfully
 * * `SyncResult::ErrorInvalidInput` - Invalid UUID format or null pointers
 * * `SyncResult::ErrorSerialization` - Invalid JSON content
 * * `SyncResult::ErrorDatabase` - Database operation failed
 * * `SyncResult::ErrorConnection` - Sync to server failed (document saved locally)
 *
 * # Note
 * If a document with the specified ID already exists, it will be overwritten (upsert behavior).
 * Use this for ID preservation during data migration or import scenarios.
 *
 * # Safety
 * Caller must ensure engine is valid, document_id and content_json are valid C strings
 */
enum ReplicantSyncResult replicant_create_document_with_id(struct Replicant *engine,
                                                           const char *document_id,
                                                           const char *content_json);

/**
 * Update an existing document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID to update
 * * `content_json` - New document content as JSON string
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid and both document_id and content_json are valid C strings
 */
enum ReplicantSyncResult replicant_update_document(struct Replicant *engine,
                                                   const char *document_id,
                                                   const char *content_json);

/**
 * Delete a document
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID to delete
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid and document_id is a valid C string
 */
enum ReplicantSyncResult replicant_delete_document(struct Replicant *engine,
                                                   const char *document_id);

/**
 * Free a C string allocated by this library
 *
 * # Safety
 * Caller must ensure the string was allocated by this library and hasn't been freed
 */
void replicant_string_free(char *s);

/**
 * Get the engine's own frozen user UUID
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_user_id` - Output pointer for user UUID string (caller must free with replicant_string_free)
 *
 * # Returns
 * * SyncResult::Success if the user ID was retrieved
 * * SyncResult::ErrorInvalidInput if engine or out_user_id is null
 * * SyncResult::ErrorDatabase if the user ID could not be read
 *
 * # Safety
 * Caller must ensure engine is valid and out_user_id is a valid pointer
 */
enum ReplicantSyncResult replicant_get_user_id(struct Replicant *engine,
                                               char **out_user_id);

/**
 * Get library version string
 */
char *replicant_get_version(void);

/**
 * Register a callback for document events (Created, Updated, Deleted)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for document events
 * * `context` - User-defined context pointer passed to callback
 * * `event_filter` - Optional filter: 0=Created, 1=Updated, 2=Deleted, -1=all document events
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_document_callback(struct Replicant *engine,
                                                              DocumentEventCallback callback,
                                                              void *context,
                                                              int32_t event_filter);

/**
 * Register a callback for sync events (Started, Completed)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for sync events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_sync_callback(struct Replicant *engine,
                                                          SyncEventCallback callback,
                                                          void *context);

/**
 * Register a callback for error events (SyncError)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for error events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_error_callback(struct Replicant *engine,
                                                           ErrorEventCallback callback,
                                                           void *context);

/**
 * Register a callback for connection events (Lost, Attempted, Succeeded)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for connection events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_connection_callback(struct Replicant *engine,
                                                                ConnectionEventCallback callback,
                                                                void *context);

/**
 * Register a callback for conflict events (ConflictDetected)
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - C callback function to invoke for conflict events
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_conflict_callback(struct Replicant *engine,
                                                              ConflictEventCallback callback,
                                                              void *context);

/**
 * Register a callback for IdentityChanged events
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `callback` - Function to call when the server-authoritative id is adopted
 * * `context` - User-defined context pointer passed to callback
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is valid, callback is a valid function pointer, and context pointer outlives the callback registration
 */
enum ReplicantSyncResult replicant_register_identity_callback(struct Replicant *engine,
                                                              IdentityEventCallback callback,
                                                              void *context);

/**
 * Process all queued events on the current thread
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_processed_count` - Output pointer for number of events processed (optional)
 *
 * # Returns
 * * CSyncResult indicating success or failure
 *
 * # Important
 * This function MUST be called on the same thread where callbacks were registered.
 * Events are queued from any thread but only processed on the callback thread.
 *
 * # Safety
 * Caller must ensure engine is valid and out_processed_count points to valid memory (if not null)
 */
enum ReplicantSyncResult replicant_process_events(struct Replicant *engine,
                                                  uint32_t *out_processed_count);

/**
 * Get a document by ID
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `document_id` - Document ID as UUID string
 * * `out_content` - Output pointer for document JSON content (caller must free with replicant_string_free)
 *
 * # Returns
 * * SyncResult::Success if document found and content returned
 * * SyncResult::ErrorInvalidInput if document not found or invalid ID
 *
 * # Safety
 * Caller must ensure engine is valid, document_id is a valid C string, and out_content is a valid pointer
 */
enum ReplicantSyncResult replicant_get_document(struct Replicant *engine,
                                                const char *document_id,
                                                char **out_content);

/**
 * Get all documents as a JSON array
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_documents` - Output pointer for JSON array of documents (caller must free with replicant_string_free)
 *
 * # Returns
 * * SyncResult::Success with JSON array (empty array [] if no documents)
 *
 * # Safety
 * Caller must ensure engine is valid and out_documents is a valid pointer
 */
enum ReplicantSyncResult replicant_get_all_documents(struct Replicant *engine,
                                                     char **out_documents);

/**
 * Get all document ids as a JSON array
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `include_deleted` - If true, include tombstoned (deleted) documents
 * * `out_ids` - Output pointer for JSON array of id strings (caller must free with replicant_string_free)
 *
 * # Returns
 * * SyncResult::Success with JSON array (empty array [] if no documents)
 *
 * # Safety
 * Caller must ensure engine is valid and out_ids is a valid pointer
 */
enum ReplicantSyncResult replicant_get_all_document_ids(struct Replicant *engine,
                                                        bool include_deleted,
                                                        char **out_ids);

/**
 * Get the count of local documents
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_count` - Output pointer for document count
 *
 * # Returns
 * * SyncResult::Success with count written to out_count
 *
 * # Safety
 * Caller must ensure engine is valid and out_count is a valid pointer
 */
enum ReplicantSyncResult replicant_count_documents(struct Replicant *engine, uint64_t *out_count);

/**
 * Check if the sync engine is connected to the server
 *
 * # Arguments
 * * `engine` - Sync engine instance
 *
 * # Returns
 * * true if connected, false if disconnected or engine is null
 *
 * # Safety
 * Caller must ensure engine was created by replicant_create
 */
bool replicant_is_connected(struct Replicant *engine);

/**
 * Get the count of documents pending sync to server
 *
 * # Arguments
 * * `engine` - Sync engine instance
 * * `out_count` - Output pointer for pending document count
 *
 * # Returns
 * * SyncResult::Success with count written to out_count
 *
 * # Safety
 * Caller must ensure engine is valid and out_count is a valid pointer
 */
enum ReplicantSyncResult replicant_count_pending_sync(struct Replicant *engine,
                                                      uint64_t *out_count);

/**
 * Configure which JSON paths to index for full-text search
 *
 * # Arguments
 * * `engine` - Replicant client instance
 * * `paths_json` - JSON array of JSON paths to index (e.g., '["$.body", "$.notes"]')
 *
 * # Returns
 * * SyncResult::Success if configuration succeeded
 * * SyncResult::ErrorInvalidInput if paths_json is invalid
 * * SyncResult::ErrorDatabase if index rebuild fails
 *
 * # Note
 * This replaces any existing configuration and rebuilds the search index.
 *
 * # Safety
 * Caller must ensure engine is valid and paths_json is a valid C string
 */
enum ReplicantSyncResult replicant_configure_search(struct Replicant *engine,
                                                    const char *paths_json);

/**
 * Search documents using FTS5 full-text search
 *
 * # Arguments
 * * `engine` - Replicant client instance
 * * `query` - FTS5 query string (e.g., "music", "tun*", "\"exact phrase\"")
 * * `limit` - Maximum number of results (0 for default of 100)
 * * `out_documents` - Output pointer for JSON array of matching documents
 *
 * # Returns
 * * SyncResult::Success with JSON array in out_documents
 * * SyncResult::ErrorInvalidInput if query is invalid
 * * SyncResult::ErrorDatabase if search fails
 *
 * # FTS5 Query Syntax
 * * Simple terms: "music" matches documents containing "music"
 * * Prefix: "tun*" matches "tuning", "tune", etc.
 * * Phrase: "\"equal temperament\"" matches exact phrase
 * * Boolean: "music AND theory", "piano OR keyboard"
 * * Column filter: "title:beethoven" searches only title field
 *
 * # Safety
 * Caller must ensure engine is valid, query is a valid C string,
 * and out_documents is a valid pointer. Caller must free result with replicant_string_free.
 */
enum ReplicantSyncResult replicant_search_documents(struct Replicant *engine,
                                                    const char *query,
                                                    uint32_t limit,
                                                    char **out_documents);

/**
 * Rebuild the full-text search index
 *
 * # Arguments
 * * `engine` - Replicant client instance
 *
 * # Returns
 * * SyncResult::Success if rebuild succeeded
 * * SyncResult::ErrorDatabase if rebuild fails
 *
 * # Note
 * This is called automatically by replicant_configure_search, but can be
 * called manually if needed (e.g., after bulk document imports).
 *
 * # Safety
 * Caller must ensure engine is valid
 */
enum ReplicantSyncResult replicant_rebuild_search_index(struct Replicant *engine);

/**
 * Requests an enrollment token be emailed to `email`. Standalone HTTP call
 * (no engine handle); runs on a dedicated thread with its own short-lived
 * runtime so this is safe to call even from inside an async runtime context.
 *
 * BLOCKING: waits for the HTTP round-trip (connect ~10s / request ~30s
 * timeouts). TODO(#40): add a completion-callback async variant
 * (`replicant_enroll_request_async`) so consumers don't block a caller thread.
 *
 * # Safety
 * `base_url` and `email` must be valid, non-null C strings.
 */
enum ReplicantSyncResult replicant_enroll_request(const char *base_url, const char *email);

/**
 * Exchanges an enrollment token for a per-user credential. On success writes
 * the api_key, secret, and canonical user id (36-char UUID string) into the
 * out buffers; each `*_cap` is the writable size of its buffer in bytes and
 * the call fails (without overflowing) when a value does not fit.
 *
 * BLOCKING: waits for the HTTP round-trip (connect ~10s / request ~30s
 * timeouts). TODO(#40): add a completion-callback async variant
 * (`replicant_enroll_claim_async`) so consumers don't block a caller thread.
 *
 * # Safety
 * All string pointers must be valid, non-null C strings; each out pointer
 * must reference a writable buffer of at least its stated capacity.
 */
enum ReplicantSyncResult replicant_enroll_claim(const char *base_url,
                                                const char *email,
                                                const char *token,
                                                char *out_api_key,
                                                uintptr_t api_key_cap,
                                                char *out_secret,
                                                uintptr_t secret_cap,
                                                char *out_user_id,
                                                uintptr_t user_id_cap);

/**
 * Loads stored credentials from `data_dir`. Returns Success and fills the
 * out buffers (api_key, secret, canonical user id), or ErrorDatabase if none
 * are stored / unreadable. Each `*_cap` is the writable size of its buffer;
 * the call fails (without overflowing) when a value does not fit.
 *
 * # Safety
 * `data_dir` must be a valid, non-null C string; each out pointer must
 * reference a writable buffer of at least its stated capacity.
 */
enum ReplicantSyncResult replicant_load_credentials(const char *data_dir,
                                                    char *out_api_key,
                                                    uintptr_t api_key_cap,
                                                    char *out_secret,
                                                    uintptr_t secret_cap,
                                                    char *out_user_id,
                                                    uintptr_t user_id_cap);

/**
 * Stores credentials to `data_dir` (encrypted at rest). `user_id` is the
 * canonical id delivered by enrollment claim (36-char UUID string); a nil or
 * unparseable id is rejected — credentials are never stored without a real
 * identity.
 *
 * # Safety
 * All pointers must be valid, non-null C strings.
 */
enum ReplicantSyncResult replicant_store_credentials(const char *data_dir,
                                                     const char *api_key,
                                                     const char *secret,
                                                     const char *user_id);

/**
 * Clears any stored credentials in `data_dir`.
 *
 * # Safety
 * `data_dir` must be a valid, non-null C string.
 */
enum ReplicantSyncResult replicant_clear_credentials(const char *data_dir);

/**
 * Trigger a test event (for development/testing purposes)
 *
 * # Arguments
 * * `engine` - Replicant client instance
 * * `event_type` - Event type to emit (0-7)
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Event Types
 * * 0 - DocumentCreated
 * * 1 - DocumentUpdated
 * * 2 - DocumentDeleted
 * * 3 - SyncStarted
 * * 4 - SyncCompleted
 * * 5 - SyncError
 * * 6 - ConflictDetected
 * * 7 - ConnectionLost
 * * 8 - ConnectionAttempted
 * * 9 - ConnectionSucceeded
 *
 * # Safety
 * Caller must ensure engine is a valid pointer
 */
enum ReplicantSyncResult replicant_emit_test_event(struct Replicant *engine, int32_t event_type);

/**
 * Trigger multiple test events in sequence (for stress testing callbacks)
 *
 * # Arguments
 * * `engine` - Replicant client instance
 * * `count` - Number of events to emit (1-100)
 *
 * # Returns
 * * SyncResult indicating success or failure
 *
 * # Safety
 * Caller must ensure engine is a valid pointer
 */
enum ReplicantSyncResult replicant_emit_test_event_burst(struct Replicant *engine, int32_t count);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#ifdef __cplusplus
} // namespace replicant
#endif // __cplusplus

#endif /* REPLICANT_H */
